### ISSUE TITLE
Would you update this  repository？

### ISSUE THREAD

**Issue by jeejeeli** [gurkirt/realtime-action-detection#1]
Thanks~~

**Comment by gurkirt** [comment]
soon!
Thanks for your patience

**Comment by SaifAlabachi** [comment]
I like the idea, would you upload the code please?

**Comment by gurkirt** [comment]
Hi Guys, thank you very much for your patience. I found a bug in my code which has an effect on performance. It increased a little. I am in the process of verifying the numbers and would upload the code soon!. Hopefully by this weekend.

**Comment by zhujiagang** [comment]
Thank you!

**Comment by gurkirt** [comment]
I need to train the networks again to upload the trained model. I will upload as soon as I can. Thank you.

**Comment by gurkirt** [comment]
Hi Guys, Code is up now :) Have fun :)
