### ISSUE TITLE
Info related to mean, nwsum-plus, and cat fusion

### ISSUE THREAD

**Issue by zhanghaoinf** [gurkirt/realtime-action-detection#10]
Hi, @gurkirt , thank you for sharing the source codes, I am running and reading the online-tubes part, and want to consult few questions about the codes.
1. fusion methods: Does 'nwsum-plus' and 'cat' separately refers to 'boost-fusion' and 'union-set' as in your  ICCV paper? And does the 'mean' fusion has the same meaning as in Kalogeiton et al. [5] ? (averaging scores of anchors from the two-stream, but retaining boundingbox generated by RGB.). 

2. It seem that there are some minor problems relating to the hard-coded parameters: 
2.1 In script test-ucf24.py, line 188, "args.listid = '099'" seems to be "args.listid = '01'" for UCF24 dataset ?
2.2 In script initDatasetOpts.m, line 45 and initDatasetOptsFused.m, line 74, "annots.mat" seems to be "finalAnnots.mat" ?

**Comment by gurkirt** [comment]
Ans 1. yes you are right.
Ans 2. I think you are right I go through it and push the fixed changes.
