### ISSUE TITLE
How much space is needed？

### ISSUE THREAD

**Issue by jack99541008** [gurkirt/realtime-action-detection#12]
Hi. How much space is needed to run test-ucf24.py ?
Is it 3TB enough?

**Comment by gurkirt** [comment]
yeah, should be more than enough!

**Comment by jack99541008** [comment]
Thanks. and...
1. How to visualize the result of action tube (result video)?
2. Is it necessary to use brox-folder? ,could I only use rgb-folder to run your code?

**Comment by gurkirt** [comment]
1.  check 'matlab-online-display' for display and it is mentioned in readme.md
2. No, it is up to you. If you want to reproduce the result in the paper then you would need brox otherwise you can just play with RGB. Please walk through readme and `train-ucf24.py` and `test-ucf24.py`
