### ISSUE TITLE
Inquiry about runtime

### ISSUE THREAD

**Issue by aelnouby** [gurkirt/realtime-action-detection#13]
Hi,

I had a question about the reported runtime. Did you use any batch processing or is the reported number using only one frame at a time ? Additionally, the runtime for DIS-Fast you reported is 7 ms while it in the Flownet:2.0 paper they reported 70ms. I am aware you used CPU multiprocessing, but was the parallelization  applied to different images or to the same image in order to get a 10x speed up ?

Thanks.

**Comment by gurkirt** [comment]
For DIS-FAST, it is 7ms to compute flow if you don't consider the image loading and saving part, I am not aware how Flownet:2.0 reports it, there are multiple settings fastest setting only take 2ms but that doesn't include memory allocating time for creating a pyramid. We include pyramid creation time but not the image loading. Also, we used very slightly slower version than fastest one, you can see that in DIS-FAST code. 

For SSD, we used a batch size of 4 to process and reported time using caffe --time tool. If you were to implement complete online version it might be bit slower but I think it would still be real-time at least around 30fps with a batch size of 1, you can cross verify that from Figure 5 in https://arxiv.org/pdf/1611.10012.pdf. I remember getting similar speed numbers when I was testing timing numbers.

**Comment by aelnouby** [comment]
Thanks so much for your reply. I am about to submit a paper that will mention your work so I wanted to be accurate.

**Comment by gurkirt** [comment]
Good Luck!
