### ISSUE TITLE
How to detect action on new (unseen) video frames

### ISSUE THREAD

**Issue by chandra-siri** [gurkirt/realtime-action-detection#14]
Can anyone help me how to detect an action  and classify into a class (from given 24 classes) for a new (unseen) video frames. I've gone through the code it does it for UCF-24 dataset.. there was no option to provide our data,... and code seems to be tailored to laod UCF-24.

**Comment by gurkirt** [comment]
Thank you for interest in our work. 

If you want to work with new dataset then you. The only place you need to make changes in data/ucf24.py which is same as pytorch's torch.utils.data.Dataset class. So if you want you can use any of dataset provided by pytorch or use them inspiration.
