### ISSUE TITLE
Frame ratios for each class

### ISSUE THREAD

**Issue by zhujiagang** [gurkirt/realtime-action-detection#15]
https://github.com/gurkirt/realtime-action-detection/blob/0e56ce769794e1e9d4526b7fb46d80ecdb796330/data/ucf24.py#L82
How do you change the above class ratios to the following?
https://github.com/gurkirt/realtime-action-detection/blob/0e56ce769794e1e9d4526b7fb46d80ecdb796330/data/ucf24.py#L84

Is there any performance improvment after this change?

**Comment by gurkirt** [comment]
There shouldn't be substantial change as long as classes are balanced.
However, it is about 1% video-mAP change if ratios are all ones.

**Comment by jiaozizhao** [comment]
Hi, could you explain how did you get the ratios numbers? Is it for re-balancing the samples of different classes? Could you give more explanation, please? Thank you very much.

**Comment by gurkirt** [comment]
Please follow the code;
If you uncomment line 85 https://github.com/gurkirt/realtime-action-detection/blob/0e56ce769794e1e9d4526b7fb46d80ecdb796330/data/ucf24.py#L85 

you will get newratios at https://github.com/gurkirt/realtime-action-detection/blob/0e56ce769794e1e9d4526b7fb46d80ecdb796330/data/ucf24.py#L153

How many sample you want per class is defined at https://github.com/gurkirt/realtime-action-detection/blob/0e56ce769794e1e9d4526b7fb46d80ecdb796330/data/ucf24.py#L149

**Comment by zhujiagang** [comment]
@gurkirt If ratios are all ones, perhaps It would take more time than now, maybe more than four days with one gpu? How much time it takes you to finish one training?

**Comment by gurkirt** [comment]
I trained for 120k iterations. That is a constant time depending upon your
hardware. I don't remember the excat difference in numbers but wasn't a
lot (<1%) for 120k iterations with ratios equal to ones.
