### ISSUE TITLE
Adding constant scalar to softmax over action paths

### ISSUE THREAD

**Issue by Feynman27** [gurkirt/realtime-action-detection#17]
@gurkirt I'm probably missing something, but what is the point of adding 20 to the softmax probabilities [here](https://github.com/gurkirt/realtime-action-detection/blob/bbad466ce7cfe7676ef461630cf693645cffe1de/online-tubes/gentube/PARactionPathSmoother.m#L68).

**Comment by gurkirt** [comment]
doesn't ave any effect. It is meaningless in this context, earlier I used
it with svm scores at that time and it helped there.

**Comment by Feynman27** [comment]
Great, thanks. Closing the issue.
