### ISSUE TITLE
Temproal labeling

### ISSUE THREAD

**Issue by jiaozizhao** [gurkirt/realtime-action-detection#18]
1. Hi, do you think your temporal labeling also works for multiple-label per-frame results or not? 
2. I found the tube results visualization code in the folder 'matlab-online-display' didn't include temporal labeling.

**Comment by gurkirt** [comment]
1. Yes, it should work for multiple labels, As labelling is done for each class independently. 
2. Sorry, that doesn't include visualisation for temporal labelling. Please refer to https://github.com/gurkirt/realtime-action-detection/issues/2, where zhujiagang explain about his PR('matlab-online-display').

**Comment by jiaozizhao** [comment]
I tried it on multiple-label task and the results are not good. Anyway, thanks a lot. I will try to understand it.

**Comment by gurkirt** [comment]
You need to use binary cross entrophy instead of softmax.

**Comment by jiaozizhao** [comment]
Yes, I did. I mean only temporal labeling is not good. Others are good.

**Comment by gurkirt** [comment]
Good Luck!
