### ISSUE TITLE
One Question about  'import build_ssd'

### ISSUE THREAD

**Issue by Zephyr06** [gurkirt/realtime-action-detection#19]
Hello, I just begun to learn to use pytorch, and met this problem when trying to execute the code:

Traceback (most recent call last):
  File "test-ucf24.py", line 15, in <module>
    from ssd import build_ssd
  File "/home/rfb/0RealTimeActionDetection/realtime-action-detection/ssd.py", line 205
    mbox[str(size)], num_classes), num_classes)
SyntaxError: only named arguments may follow *expression

So, could anyone give me a hand? Thanks a lot!

**Comment by gurkirt** [comment]
It worked fine for me, It was just a warning to me. Maybe it is a version
problem.

Try replacing
https://github.com/gurkirt/realtime-action-detection/blob/master/ssd.py#L203

with SSD(multibox(vgg(base[str(size)], 3), add_extras(extras[str(size)],
1024), mbox[str(size)], num_classes), num_classes)

**Comment by Zephyr06** [comment]
Thank you a lot, it works out for me!
