### ISSUE TITLE
The implemented code seems dosen't operate action detection in an online fashion

### ISSUE THREAD

**Issue by hjjpku** [gurkirt/realtime-action-detection#20]
It seems that you do the action path generation across time span first and than perform the temporal trimming, which makes the code dosen't perform action detection in an online fashion.
Do you plan to release the code of online viterbi for online temporal trimming you mentioned in your paper?

**Comment by irexyc** [comment]
The online code are stored in matlab-online-display/, you can refer to #2

**Comment by hjjpku** [comment]
THX

**Comment by gurkirt** [comment]
HI @hjjpku  @irexyc 
Linking part is completely online https://github.com/gurkirt/realtime-action-detection/blob/master/online-tubes/actionpath/incremental_linking.m; you only need to put together temporal labeling with from https://github.com/gurkirt/realtime-action-detection/blob/master/online-tubes/gentube/dpEM_max.m;

So, no, temporal trimming and linking are not put together like explained in the paper. It was a messing setup and I don't have time to clean up. 

I am aware that zhujiagang has implemented display functionality but I don't think he implemented temporal trimming as well. Have a look at https://github.com/Feynman27/realtime-action-detection.

**Comment by irexyc** [comment]
@gurkirt Thanks for your explanation.
@hjjpku My bad, I just read the online-tubes code.

**Comment by hjjpku** [comment]
Thanks, anyway @gurkirt  @irexyc
