### ISSUE TITLE
the problem about training SSD

### ISSUE THREAD

**Issue by NicoleNicoleXiang** [gurkirt/realtime-action-detection#22]
hello,
when i am tryring to train ssd ,there is an error about the type of tensor for objects is not suitable.
for instance, 
 File "/home/xlp/.local/lib/python3.5/site-packages/torch/tensor.py", line 320, in __rdiv__
 return self.reciprocal() * other
RuntimeError: reciprocal is not implemented for type torch.cuda.LongTensorh
how should i solve this problem?thanks.

**Comment by JingliangGao** [comment]
@gurkirt Maybe you should give his elegant lady a hand as soon as possible :)

**Comment by gurkirt** [comment]
Hi @NicoleNicoleXiang, thank you for your interest. 
I can not help with this information can you please provide some more context so I can reproduce the problem you are facing.

**Comment by NicoleNicoleXiang** [comment]
Hi，@gurkirt  
thanks for replying, i have solved the problem resulted for the version of pytorch by changing its 4.0 to 2.0.

**Comment by gurkirt** [comment]
Like it is mentioned in the README file. This repo is based on pytorch 3.0.

**Comment by NicoleNicoleXiang** [comment]
yes

**Comment by gurkirt** [comment]
@NicoleNicoleXiang , if you are still looking to use it. I updated the code to pytorch 1.2.
