### ISSUE TITLE
confusion about temporal labelling

### ISSUE THREAD

**Issue by ray342649093** [gurkirt/realtime-action-detection#23]
it seems like we can have a better video-level performance without the temporal labelling process. So why would you like to use the temporal labelling?

**Comment by gurkirt** [comment]
yes, you are absolutely right. I found it after the fact. You can see the new results in table 1 of https://arxiv.org/pdf/1808.00297.pdf. Also, check out the Table 2 where temporal trimming helps.

**Comment by ray342659093** [comment]
@gurkirt Thank you for reply. Glad to see another paper on action detection. Is it published in ECCV?
