### ISSUE TITLE
Asking about Optical Flow.

### ISSUE THREAD

**Issue by KhanhDinhDuy** [gurkirt/realtime-action-detection#24]
Hello,
I would like to ask a question about Brox Optical Flow.
I could not reproduce the results as your provided dataset when using your github https://github.com/gurkirt/optical-flow. Could you give me some suggestion about this part?
Thank you,
Khanh

**Comment by gurkirt** [comment]
I computed optical flow a few years back using the above repo. 
I am sure if you train on new optical flow images generated should produce similar results.
First, verify that you can reproduce results using provided optical flow images.

**Comment by KhanhDinhDuy** [comment]
Dear gurkirt,
Here is your dataset:
+++++++++++
Basketball/v_Basketball_g01_c01
+++++++++++
![00001](https://user-images.githubusercontent.com/29646642/44142528-9c68ebe8-a0aa-11e8-9600-1a92039dee5c.jpg)

Here is mine when using your repo
+++++++++++
cache/v_Basketball_g01_c01
+++++++++++

![00001](https://user-images.githubusercontent.com/29646642/44142572-ce2a3ab0-a0aa-11e8-93b5-3d46d807858c.jpg)

You can see the difference. I am not sure whether this one will have bad effect or not.

**Comment by gurkirt** [comment]
Yes, you are right. Any motionless frame in the neighbourhood of 5 frames is replaced with a frame with some motion. 
If you go to https://bitbucket.org/sahasuman/bmvc2016_code/src/master/
there you can use 'compute_optical_flow_images/processMotionLessFrames.m' to do this for you.

**Comment by KhanhDinhDuy** [comment]
Dear gurkirt,
Thank you for your response.
Could you please share the code for the DIS optical flow calculation?
I am using these codes to generate Fast-images:
https://github.com/opencv/opencv_contrib/blob/master/samples/python2/dis_opt_flow.py
https://github.com/opencv/opencv_contrib/blob/master/modules/optflow/samples/dis_opticalflow.cpp
But got different results with your prepared images.
Thank you,
Khanh

**Comment by gurkirt** [comment]
I used the c++ code provided by the author without any change, not OpenCV bindings. That code does not belong to me so I can't distribute it. Please go to the author's page and download the code. Also, use the parameters described in the paper and supp-material.

**Comment by KhanhDinhDuy** [comment]
Thank you.
Khanh
