### ISSUE TITLE
Convert matlab part into python query

### ISSUE THREAD

**Issue by sophia-wright-blue** [gurkirt/realtime-action-detection#26]
Hello,

Thanks for making this code available - I'm looking forward to using it. I was surprised to see that you used Matlab.

 You mention in your Todo that you plan to Convert matlab part into python. I was wondering if anyone has gotten started on doing this, and if there is a git repo for the conversion that I could contribute to.

Thanks again,

**Comment by gurkirt** [comment]
you can have a look at https://github.com/Feynman27/realtime-action-detection

**Comment by sophia-wright-blue** [comment]
Thank you for replying. I see that there are some python equivalent scripts in the repo that you mentioned, but a lot of the code in that repo is still in MATLAB. Unfortunately, I don't have access to MATLAB. so I guess, I'm going to have a to convert the code to Python.

A slightly related question - have you tried to deploy this model in production? or have you received any feedback from someone who has tried to operationalize this model?

Thanks again for releasing this code, and for replying to my query.

**Comment by gurkirt** [comment]
nope

**Comment by sophia-wright-blue** [comment]
ok, thank you,

**Comment by zsz01** [comment]
I‘m very sorry to borrow you! If I can't have the matlab environment in my server, I find that you mention the python version,but I try it and it don't work. The results is  :
root@4fb27e7d1861:/opt/pytorch/realtime-action-detection-master/online-tubes# python I01onlineTubes.py
root@4fb27e7d1861:/opt/pytorch/realtime-action-detection-master/online-tubes#

I get nothing printing.

Can you give me other way to bulid onlinetubes!
Thanke you.
Best wishes!

**Comment by gurkirt** [comment]
I am sorry, you need to read the README and follow the step. TO run the current version of the code you will need Matlab.
