### ISSUE TITLE
Training with other dataset.

### ISSUE THREAD

**Issue by KhanhDinhDuy** [gurkirt/realtime-action-detection#27]
Hello,
This project trained with UCF24 dataset with 320x240 images.
Can I combine this dataset with one more class which will be crawled from Youtube, 1280x720 images?
I think it is possible because all the images will be resize to 300x300 for the input to the SSD model.
But I saw some unexpected changes in the annotation file, pyannot.pkl
And can we train the SSD with only one class? I don't know whether the performance will be decreased or not. 
Please give me some advice.
Thank you,
Khanh

**Comment by gurkirt** [comment]
Yes.
Yes.
What changes?
Same no changes, just one class.

**Comment by KhanhDinhDuy** [comment]
Dear gurkirt,
Thanks for your quick response.
For the new data, I annotate each frame(1280x720) and append the result to the pyannot.pkl file. Some bounding boxes are bigger than 320x240 frame, but after reading these frames for training, I check the pyannot.pkl file again, and the size of bounding boxes is changed to be smaller than 320x240 frame. I checked source code but still can not find where the changes occur.
Please help me with this.
Thank you so much,
Khanh

**Comment by KhanhDinhDuy** [comment]
Dear Gurkirt,
Sorry for this issue. I found my mistake.
Thank you,
Khanh

**Comment by KhanhDinhDuy** [comment]
Dear Gurkirt,
I have a question about new dataset.
Can I mix between images from stable camera and unstable camera and test the new video from stable camera?
Thank you,
Khanh

**Comment by gurkirt** [comment]
Sure, you can do whatever you want. I am not sure how the model would behave. Give it a shot.

**Comment by KhanhDinhDuy** [comment]
Thank you,
Khanh
