### ISSUE TITLE
How could I load the trained model

### ISSUE THREAD

**Issue by shijieS** [gurkirt/realtime-action-detection#3]
Thank you for your excellent work. I wonder how could load the trained model you have uploaded, such as:  brox-ssd300_ucf24_120000.pth

Best Wishes.

**Comment by gurkirt** [comment]
Download the model and then specify the path to model at https://github.com/gurkirt/realtime-action-detection/blob/master/test-ucf24.py#L193. Also, supply `--input-type=brox` of parameter to `test-ucf24.py`

**Comment by shijieS** [comment]
Okay, thank you for your excellent answer!

**Comment by zsz01** [comment]
When I load the model brox-ssd300_ucf24_120000.pth ,can't open file testing 120000.log

**Comment by gurkirt** [comment]
Check if you're save directory is created or not.

**Comment by zsz01** [comment]
No,my save direcory is not created,you mean than I create the svae directory by myself not by the code?
 Thanke you!

**Comment by gurkirt** [comment]
Save directory should be where program have write permission to create a directory.  Check the arguments annd see you are specfifing the correct path. I can't help without more information
