### ISSUE TITLE
Pytorch 0.2 doesn't work with newest Visdom

### ISSUE THREAD

**Issue by Maosef** [gurkirt/realtime-action-detection#30]
When getting the training started, I get something along the lines of
```
  File "/scratch1/anaconda2/envs/road/lib/python3.6/site-packages/visdom/__init__.py", line 1171, in line
    assert Y.ndim == 1 or Y.ndim == 2, 'Y should have 1 or 2 dim'
AttributeError: 'torch.DoubleTensor' object has no attribute 'ndim'

```

Looking into it (https://github.com/facebookresearch/visdom/blob/master/py/visdom/__init__.py), their support for PyTorch < 0.4 is deprecated. What version worked here?

**Comment by gurkirt** [comment]
Like mentioned in the description, the code is compatible with pytorch 0.3. Please follow the instructions

**Comment by Maosef** [comment]
The pytorch version mentioned in the beginning of the readme is 0.2. It
then says it would be compatible with "0.03" (typo?) with a "few fixes" but
those aren't described in detail later.

**Comment by gurkirt** [comment]
The code was developed within at that time visdom and pytorch 0.2 and 0.3 is not much different. I think you are getting problem form newer visdom. The error you are getting is a typecasting error. I would suggest you try some typecasting. Look at the type of current variables required in newer visdom.

**Comment by Maosef** [comment]
Typecasting is what I ended up doing, unfortunately the visdom display
remained blank. I tested their demo to be sure, which did display. The rest
of the code proceeded normally.
