### ISSUE TITLE
Appearance SSD result

### ISSUE THREAD

**Issue by kyuhyoung** [gurkirt/realtime-action-detection#32]
Thank you for sharing your work.
The following animated GIF file is the sampled images with bounding boxes of detected actions. 

https://komputervision.files.wordpress.com/2019/01/bbox.gif

 The detection is done by rgb-ssd300_ucf24_120000.pth (the pre-trained appearance SSD weights for 120000 iteration which you provided) with following commands.
  
CUDA_VISIBLE_DEVICES=0 python3 test-ucf24.py --data_root=/home/user/ucf24/ --save_root=/home/user/ucf24/ --input_type=rgb --eval_iter=120000

As you can see, its detection rate is very low except few classes such as 'surfing' and 'jetski'.  Is this normal ?  It seems that it fails to make big candidate bounding boxes when a person is so close to the camera that he/she appears as pretty big.  It only works well for 'surfing' and 'jetski' where the people in the images are small enough.
Of course I have to go thru the remaining process which is fusion with optical flow SSD and tube generation.  However, I was wondering if I am doing wrong or 120000 iteration is not enough, so more training is needed.

Following is the average precisions of appearance SSD for each class on 159289 test images.

Basketball : 0.005688362254987029
BasketballDunk : 0.059442425139795585
Biking : 0.027080132217020384
CliffDiving : 0.09571676832006965
CricketBowling : 0.007188381472302061
Diving : 0.0027860880597105134
Fencing : 0.00010385603971070008
FloorGymnastics : 0.10125374519594244
GolfSwing : 0.0
HorseRiding : 0.012732889758008315
IceDancing : 1.0259629201686981e-05
LongJump : 0.018733521925503246
PoleVault : 0.011395145119329191
RopeClimbing : 0.022515197847725814
SalsaSpin : 0.0
SkateBoarding : 0.033668873961642254
Skiing : 0.35775074128159023
Skijet : 0.5063684722953027
SoccerJuggling : 0.0
Surfing : 0.6024563891531864
TennisSwing : 0.06753013234296809
TrampolineJumping : 2.3870315645686263e-06
VolleyballSpiking : 0.000479302362317051
WalkingWithDog : 0.0002781709791225087

MEANAP:::=>0.08054922

**Comment by gurkirt** [comment]
I regret to say that you are doing something wrong, check your input data and annotations.

**Comment by kyuhyoung** [comment]
Thanks a lot.

My mistake was using pytorch 0.4 instead of 0.3 which you recommended.  
Using pytorch 0.4, I modified your nms function to get rid of some error messages and that was my fault.

Now I am using pytorch 0.3 and got the appearance SSD result as following.

Evaluating detections for itration number  120000
Evaluating for  159289 frames
Basketball : 1323.0 : 31152 : 0.2413438042102325
BasketballDunk : 1409.0 : 61182 : 0.4369468622795827
Biking : 11911.0 : 36157 : 0.8097896377613099
CliffDiving : 2232.0 : 244064 : 0.4430538854944991
CricketBowling : 1562.0 : 24728 : 0.31249569599252053
Diving : 5168.0 : 43951 : 0.7852504962032385
Fencing : 9564.0 : 17069 : 0.8678970439204212
FloorGymnastics : 5519.0 : 65128 : 0.8440679201516753
GolfSwing : 4344.0 : 29907 : 0.48671023806366587
HorseRiding : 8496.0 : 40068 : 0.9380926355364259
IceDancing : 22474.0 : 31834 : 0.7071715860812628
LongJump : 4480.0 : 39568 : 0.5709773422450677
PoleVault : 7114.0 : 261038 : 0.45287946342998797
RopeClimbing : 5691.0 : 31293 : 0.8232116657532236
SalsaSpin : 17131.0 : 29175 : 0.6683728222347487
SkateBoarding : 4832.0 : 57843 : 0.6860933935765536
Skiing : 8976.0 : 72212 : 0.7255935358757147
Skijet : 7319.0 : 99475 : 0.8551125343782982
SoccerJuggling : 12271.0 : 31297 : 0.7529002766113964
Surfing : 5851.0 : 100810 : 0.840512687571842
TennisSwing : 2876.0 : 19827 : 0.31594462688845687
TrampolineJumping : 11713.0 : 22089 : 0.6165808730071624
VolleyballSpiking : 1131.0 : 44834 : 0.3042450455587059
WalkingWithDog : 7193.0 : 42286 : 0.7712994733403808

MEANAP:::=>0.6356893
