### ISSUE TITLE
Problem in running

### ISSUE THREAD

**Issue by LearningEnthusiatic** [gurkirt/realtime-action-detection#36]
Hello,
Is CUDA9 gtx 1050 with 16 gb RAM and 8 gb GPU memory sufficient to run the code?
As  i am getting cuda out of memory error even when i am running test-ucf24.py with pre-trained model.
Also pytorch version 0.3 is not available for windows.
Meanwhile can you please share the detections (google drive) obtained from test-ucf24.py. It would be a great help to proceed further.

**Comment by gurkirt** [comment]
You can reduce the batch size. Look within the script.
I have no plan to support windows or upgrade this code to pytorch1.0. 
You can have look at https://github.com/gurkirt/AMTNet.pytorch once I am done with that. 
Sorry, unfortunately, I do not have time and resources to compute detections for you, I cleaned up the old cache as well.

**Comment by LearningEnthusiatic** [comment]
Okay. Thanks for your help :)

**Comment by gurkirt** [comment]
@LearningEnthusiatic, it works with pytorch 1.2 on ubuntu. Might help in adoption to windows.
