### ISSUE TITLE
Question about label/

### ISSUE THREAD

**Issue by mahdkook** [gurkirt/realtime-action-detection#37]
Hello,
I notice that the label files do not match the RGB images. For example, there are 141 RGB images in v_Basketball_g01_c01 file, but only 43 label files in label/ range 09 to 51. Can you explain the structure of train data?
Thanks.

**Comment by gurkirt** [comment]
Only certain part of video might contain actions, that is why only that part of the video is labeled. It is untrimmed setting in case of UCF24 and trimmed in case of JHMDB-21.

**Comment by mahdkook** [comment]
Thanks for your reply!
I have another question. The optical flow is computed by successive frames, so the amount of optical flow images is smaller the RGB images. Why they own the same number in the data you offered?

**Comment by gurkirt** [comment]
I think we replicate the last frame as it is to have n+1 frames while computing optical flow.

**Comment by mahdkook** [comment]
Got it. Thanks!
