### ISSUE TITLE
problems about test just useing one action of ucf24 which you provided

### ISSUE THREAD

**Issue by zsz01** [gurkirt/realtime-action-detection#39]
Hello,when I use one action of ucf24 to detet. I changed the data/ucf24.py :class={'BasketBall'}
and I have the problem:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 482, in load_state_dict
    own_state[name].copy_(param)
RuntimeError: invalid argument 2: sizes do not match at /pytorch/torch/lib/THC/THCTensorCopy.cu:31

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test-ucf24.py", line 224, in <module>
    main()
  File "test-ucf24.py", line 198, in main
    net.load_state_dict(torch.load(trained_model_path))
  File "/usr/local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 487, in load_state_dict
    .format(name, own_state[name].size(), param.size()))
RuntimeError: While copying the parameter named conf.0.weight, whose dimensions in the model are torch.Size([44, 512, 3, 3]) and whose dimensions in the checkpoint are torch.Size([100, 512, 3, 3]).

**Comment by gurkirt** [comment]
check the number of classes you used to build the model.

**Comment by zsz01** [comment]
you mean that when I train the model ,I should use one action to train the models?

**Comment by gurkirt** [comment]
Sorry, I can not help with custom solutions, please figure it out.
