### ISSUE TITLE
Could I save the labeled result image

### ISSUE THREAD

**Issue by shijieS** [gurkirt/realtime-action-detection#4]
Hi. could you please tell how to save the labeled result image after I have gotten the *actionpath.mat.

**Comment by gurkirt** [comment]
I am not sure what you mean here? Do mean you mean that you want to plot them?
As it is a Malab file you could just plot in matlab.

**Comment by shijieS** [comment]
I mean how to show the action path in the videos, just like your demo videos on youtube. I know the matlab statement.

**Comment by gurkirt** [comment]
For that you not need action paths, but final tubes smoothed by action path smoother. 

Xmldata, a structure on [line 116](https://github.com/gurkirt/realtime-action-detection/blob/master/online-tubes/I01onlineTubes.m#L116), wich contains multiple tubes for each video. you need to pick video then you can plot it's tubes frame-by-frame. 
Each tube has start and end time, bouning boxes from start to end frame of the tube, tube label and scroe. Now you can plot the tube from start frame to end frame of the tubes. You can plot multiple tubes in same manner.

**Comment by shijieS** [comment]
Hi, @gurkirt . Thank you for your answer. I'll try it later. I have written codes about plot actionPaths preliminary.  By the way, I am confused about the difference between action path and action tubes. Could you please explain it to me? 

The following is ploting action path codes in the video frame:
```Matlab
function action_path_viewer(data_root, save_root)
if nargin == 0
    data_root = '../../../data_root';
    save_root = '../../../save_root';
end
iteration_num_rgb = [50000];
iteration_num_flow = [50000];


% add subfolder to matlab paths
addpath(genpath('gentube/'));
addpath(genpath('actionpath/'));
addpath(genpath('eval/'));
addpath(genpath('utils/'));
model_type = 'CONV';

completeList = {...
    {'ucf24','01',{'rgb'},iteration_num_rgb,{'score'}},...
    {'ucf24','01',{'brox'},iteration_num_flow,{'score'}}...
    {'ucf24','01',{'fastOF'},iteration_num_flow,{'score'}}...
    };

alldopts = cell(2,1);
count= 1;
gap= 3;

for setind = 1 : length(completeList)
        [dataset, listid, imtypes, iteration_nums, costTypes] = enumurateList(completeList{setind});
        for ct = 1 : length(costTypes)
            costtype=costTypes{ct};
            for imtind = 1:length(imtypes)
                imgType = imtypes{imtind};
                for iteration = iteration_nums
                    for iouthresh=0.1
                        dopts = initDatasetOpts(data_root,save_root,dataset,imgType,model_type,listid,iteration,iouthresh,costtype, gap);
                        if exist(dopts.detDir, 'dir')
                            allopts{count} = dopts;
                            count = count+1
                        end
                    end
                end
            end
        end
end

for index = 1:count-1
    opts = allopts{index}
    if exist(opts.detDir, 'dir')
        showActionPath(opts, data_root)
    end
end
end

function showActionPath(dopts, data_root)
detresultpath = dopts.detDir;
costtype = dopts.costtype;
gap = dopts.gap;
videolist = dopts.vidList;
actions = dopts.actions;
saveName = dopts.actPathDir;
iouth = dopts.iouThresh;
numActions = length(actions);
nms_thresh = 0.45;
videos = getVideoNames(videolist);
NumVideos = length(videos);

colorset = jet(10);

for vid = 1 : NumVideos
    tic;
    videoID = videos{vid}
    actionPath = [saveName, videoID, '-actionpaths.mat'];
    videoDetDir = [detresultpath, videoID, '/'];
    videoSourceDir = [data_root, '/ucf24/rgb-images/',  videoID, '/']
    if exist(actionPath, 'file')
        load(actionPath);
        pathNum = length(allpaths)
        for pathID = 1:pathNum
            path = allpaths{pathID}
            % read frame
            [videoSourceDir, num2str(2, '%05d'), '.jpg']
            frameList = sortdirlist([videoSourceDir, '*.jpg']);
            frameNum = length(frameList);
            for frameID = 1 : frameNum
                framePath = [videoSourceDir, frameList{frameID}];
                % load image
                frame = imread(framePath);
                % draw all the rectangle
               [rectangleList, rectangleTubeList] = getRectangleList(path, frameID)
                            
                imshow(frame)
                rectangleNum = size(rectangleList, 1);
                for rectangleID = 1 : rectangleNum
                    hold on
                    rectangle('Position', rectangleList(rectangleID, :), 'EdgeColor', colorset(mod(rectangleID, 10)+1, :))
                    pause(0.025)
                end
            end
        end
    end
    
end
end

% get the list of all rectangles at specified frameID
function [rectangleList, rectangleTubeList] = getRectangleList(path, frameID)
tubeNum = length(path);
rectangleList = []
rectangleID = 0
rectangleTubeList = []
for tubeID = 1 : tubeNum
    startFrameID = path(tubeID).start;
    endFrameID = path(tubeID).end;
    if frameID >=startFrameID&& frameID <= endFrameID
        rectangleID = rectangleID + 1
        rectangle = path(tubeID).boxes(frameID-startFrameID+1, :);
        rectangle(3:4) = rectangle(3:4) - rectangle(1:2);
        rectangleList = [rectangleList; rectangle]
        rectangleTubeList = [rectangleTubeList; tubeID]
    end
end
end

%-- list the files in directory and sort them ----------
function list = sortdirlist(dirname)
list = dir(dirname);
list = sort({list.name});
end

% -------------------------------------------------------------------------
function [videos] = getVideoNames(split_file)
% -------------------------------------------------------------------------
fprintf('Get both lis is %s\n',split_file);
fid = fopen(split_file,'r');
data = textscan(fid, '%s');
videos  = cell(1);
count = 0;

for i=1:length(data{1})
    filename = cell2mat(data{1}(i,1));
    count = count +1;
    videos{count} = filename;
    %     videos(i).vid = str2num(cell2mat(data{1}(i,1)));
end
end

%% Function to enumrate options
function [dataset,listnum,imtypes,weights,costTypes] = enumurateList(sublist)
dataset = sublist{1}; listnum = sublist{2}; imtypes = sublist{3};
weights = sublist{4};costTypes = sublist{5};
end
```

**Comment by gurkirt** [comment]
If you read the paper it is explained there. In short, actions are mostly from start to end to the video but we want tubes which are temporally trimmed version of action paths.

**Comment by shijieS** [comment]
Get it. Thank you!

**Comment by zsz01** [comment]
> Hi. could you please tell how to save the labeled result image after I have gotten the *actionpath.mat.



> Hi, @gurkirt . Thank you for your answer. I'll try it later. I have written codes about plot actionPaths preliminary.  By the way, I am confused about the difference between action path and action tubes. Could you please explain it to me?
> The following is ploting action path codes in the video frame:
> function action_path_viewer(data_root, save_root)
> if nargin == 0
>     data_root = '../../../data_root';
>     save_root = '../../../save_root';
> end
> iteration_num_rgb = [50000];
> iteration_num_flow = [50000];
> 
> 
> % add subfolder to matlab paths
> addpath(genpath('gentube/'));
> addpath(genpath('actionpath/'));
> addpath(genpath('eval/'));
> addpath(genpath('utils/'));
> model_type = 'CONV';
> 
> completeList = {...
>     {'ucf24','01',{'rgb'},iteration_num_rgb,{'score'}},...
>     {'ucf24','01',{'brox'},iteration_num_flow,{'score'}}...
>     {'ucf24','01',{'fastOF'},iteration_num_flow,{'score'}}...
>     };
> 
> alldopts = cell(2,1);
> count= 1;
> gap= 3;
> 
> for setind = 1 : length(completeList)
>         [dataset, listid, imtypes, iteration_nums, costTypes] = enumurateList(completeList{setind});
>         for ct = 1 : length(costTypes)
>             costtype=costTypes{ct};
>             for imtind = 1:length(imtypes)
>                 imgType = imtypes{imtind};
>                 for iteration = iteration_nums
>                     for iouthresh=0.1
>                         dopts = initDatasetOpts(data_root,save_root,dataset,imgType,model_type,listid,iteration,iouthresh,costtype, gap);
>                         if exist(dopts.detDir, 'dir')
>                             allopts{count} = dopts;
>                             count = count+1
>                         end
>                     end
>                 end
>             end
>         end
> end
> 
> for index = 1:count-1
>     opts = allopts{index}
>     if exist(opts.detDir, 'dir')
>         showActionPath(opts, data_root)
>     end
> end
> end
> 
> function showActionPath(dopts, data_root)
> detresultpath = dopts.detDir;
> costtype = dopts.costtype;
> gap = dopts.gap;
> videolist = dopts.vidList;
> actions = dopts.actions;
> saveName = dopts.actPathDir;
> iouth = dopts.iouThresh;
> numActions = length(actions);
> nms_thresh = 0.45;
> videos = getVideoNames(videolist);
> NumVideos = length(videos);
> 
> colorset = jet(10);
> 
> for vid = 1 : NumVideos
>     tic;
>     videoID = videos{vid}
>     actionPath = [saveName, videoID, '-actionpaths.mat'];
>     videoDetDir = [detresultpath, videoID, '/'];
>     videoSourceDir = [data_root, '/ucf24/rgb-images/',  videoID, '/']
>     if exist(actionPath, 'file')
>         load(actionPath);
>         pathNum = length(allpaths)
>         for pathID = 1:pathNum
>             path = allpaths{pathID}
>             % read frame
>             [videoSourceDir, num2str(2, '%05d'), '.jpg']
>             frameList = sortdirlist([videoSourceDir, '*.jpg']);
>             frameNum = length(frameList);
>             for frameID = 1 : frameNum
>                 framePath = [videoSourceDir, frameList{frameID}];
>                 % load image
>                 frame = imread(framePath);
>                 % draw all the rectangle
>                [rectangleList, rectangleTubeList] = getRectangleList(path, frameID)
>                             
>                 imshow(frame)
>                 rectangleNum = size(rectangleList, 1);
>                 for rectangleID = 1 : rectangleNum
>                     hold on
>                     rectangle('Position', rectangleList(rectangleID, :), 'EdgeColor', colorset(mod(rectangleID, 10)+1, :))
>                     pause(0.025)
>                 end
>             end
>         end
>     end
>     
> end
> end
> 
> % get the list of all rectangles at specified frameID
> function [rectangleList, rectangleTubeList] = getRectangleList(path, frameID)
> tubeNum = length(path);
> rectangleList = []
> rectangleID = 0
> rectangleTubeList = []
> for tubeID = 1 : tubeNum
>     startFrameID = path(tubeID).start;
>     endFrameID = path(tubeID).end;
>     if frameID >=startFrameID&& frameID <= endFrameID
>         rectangleID = rectangleID + 1
>         rectangle = path(tubeID).boxes(frameID-startFrameID+1, :);
>         rectangle(3:4) = rectangle(3:4) - rectangle(1:2);
>         rectangleList = [rectangleList; rectangle]
>         rectangleTubeList = [rectangleTubeList; tubeID]
>     end
> end
> end
> 
> %-- list the files in directory and sort them ----------
> function list = sortdirlist(dirname)
> list = dir(dirname);
> list = sort({list.name});
> end
> 
> % -------------------------------------------------------------------------
> function [videos] = getVideoNames(split_file)
> % -------------------------------------------------------------------------
> fprintf('Get both lis is %s\n',split_file);
> fid = fopen(split_file,'r');
> data = textscan(fid, '%s');
> videos  = cell(1);
> count = 0;
> 
> for i=1:length(data{1})
>     filename = cell2mat(data{1}(i,1));
>     count = count +1;
>     videos{count} = filename;
>     %     videos(i).vid = str2num(cell2mat(data{1}(i,1)));
> end
> end
> 
> %% Function to enumrate options
> function [dataset,listnum,imtypes,weights,costTypes] = enumurateList(sublist)
> dataset = sublist{1}; listnum = sublist{2}; imtypes = sublist{3};
> weights = sublist{4};costTypes = sublist{5};
> end

hi,have you realize the code to make the actiontubes in videos just the demo in youtube,can you share the code,thank you very much
