### ISSUE TITLE
will it work for  multivariate  time series classification for example mixture of categorical and continues data? 

### ISSUE THREAD

**Issue by Sandy4321** [gurkirt/realtime-action-detection#42]
will it work for  multivariate  time series classification for example mixture of categorical and continues data? 
	for example at time t1 we have observation: red, 2.4 , 5, 12.456 and time t2: green, 3.5, 2, 45.78; time t3: black, 5.6, 7, 23.56; t4: red, 2.1, 5, 12.6 ?

**Comment by gurkirt** [comment]
I am not sure what those 3 numbers mean here. We treat observations for each class independently if that suite your case then yes. But I can not really say without knowing more about the problem statement. Multivariate could mean a lot of things.

**Comment by Sandy4321** [comment]
Multivariate could mean a lot of things.

Let's say any Multivariate example on your choice

**Comment by gurkirt** [comment]
Hi @Sandy4321, it would help if you make your example more concrete

**Comment by Sandy4321** [comment]
will it work for  multivariate  time series classification for example mixture of categorical and continues data? 
for example at time t1 we have observation: red, 2.4 , 5, 12.456 and time t2: green, 3.5, 2, 45.78; time t3: black, 5.6, 7, 23.56; t4: red, 2.1, 5, 12.6 ?
As you asked I clarify
Then 
t1 is yes, t2 is yes, t3 is no, t4 is no
Can your code classify this kind of data?

Let's say we have 2 classes yes and no

**Comment by gurkirt** [comment]
You can train a classifier your observation samples, in our cases, those are results from SSD detector, which give a score between 0 and 1 for each class, in our case that 24 classes, in your class, you have two classes (yes, no) train a binary classifier then you can apply label smoothing formulation.

**Comment by gurkirt** [comment]
basically you will need a way to translate categorical data into 0-1 by sudo-probabilistic classifier

**Comment by Sandy4321** [comment]
what is it : sudo-probabilistic classifier?
can you share link pls?

**Comment by gurkirt** [comment]
In our case that is SSD detector.

**Comment by Sandy4321** [comment]
Not clear what can be used for tabular data
Can you help find web link for 
sudo-probabilistic classifier for tabular data

**Comment by gurkirt** [comment]
Random forest is supposed to be good for categorical data. But, I am no expert in that domain.
