### ISSUE TITLE
pytorch=1.2.0 ,I got a error. I hope to get your help

### ISSUE THREAD

**Issue by Lisa20182017** [gurkirt/realtime-action-detection#43]
RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation: [torch.cuda.FloatTensor [1, 512, 38, 38]], which is output 0 of ReluBackward0, is at version 1; expected version 0 instead. Hint: enable anomaly detection to find the operation that failed to compute its gradient, with torch.autograd.set_detect_anomaly(True).

![image](https://user-images.githubusercontent.com/39552891/63757834-5592d000-c8ed-11e9-8bae-2581eeb8404b.png)

![image](https://user-images.githubusercontent.com/39552891/63758014-b5897680-c8ed-11e9-8c98-f1870c983536.png)

**Comment by gurkirt** [comment]
I have no plan to update this code to PT 1, the original code was developed in pt 0.3. Please follow the readme file.

**Comment by gurkirt** [comment]
@Lisa20182017, it should now work with pytorch 1.2. Please check and let me know it works for you now.
