### ISSUE TITLE
problem with loading pretrained weights for custom dataset with different number of classes

### ISSUE THREAD

**Issue by shashankvkt** [gurkirt/realtime-action-detection#45]
Hi,
Thank you for providing the code. I am working on a dataset which has 11 classes (10 + 1background). However, I wish to use your pretrained weights and finetune it on my dataset. Unfortunately, when I initialize the model, it does not load the weights correctly. Could you kindly share your view on how to load your trained model for a different number of classes?
Thanks.

**Comment by gurkirt** [comment]
you will need to add load_state dict function, undet SSD class which skips over loading weight of last layer. https://github.com/gurkirt/realtime-action-detection/blob/master/train-ucf24.py#L120

You can take inspiration from https://github.com/pytorch/pytorch/blob/master/torch/nn/modules/module.py#L779
