### ISSUE TITLE
Testing Pre-trained models

### ISSUE THREAD

**Issue by pranavgundewar** [gurkirt/realtime-action-detection#46]
Hi, thanks for the great work!

I was testing the model using pre-trained weights and came across this error-
![Screenshot from 2019-11-11 14-47-11](https://user-images.githubusercontent.com/37206432/68627309-4eae3f00-0492-11ea-8f6b-651e8582c1f2.png)

How to solve this error? Thank you.

**Comment by gurkirt** [comment]
Which version of pytorch are you using?

**Comment by pranavgundewar** [comment]
Hi! There was some issue with a file. I fixed it. Thanks

**Comment by daodaofr** [comment]
hi, @pranavgundewar . I got the same issue, how do you fix it ?

**Comment by pranavgundewar** [comment]
@daodaofr There was naming issue in data or pretrained model. I renamed the script and it worked for me.
