### ISSUE TITLE
Did you implement the evaluation of action early prediction in the paper

### ISSUE THREAD

**Issue by huangchaoxing** [gurkirt/realtime-action-detection#47]
HI

Did you implement the evaluation of action early prediction in the paper ?

**Comment by gurkirt** [comment]
You can use `tac` from  https://github.com/gurkirt/realtime-action-detection/blob/master/online-tubes/I01onlineTubes.m#L119

You will need to evaluate 10 different time steps.

**Comment by huangchaoxing** [comment]
> You can use `tac` from https://github.com/gurkirt/realtime-action-detection/blob/master/online-tubes/I01onlineTubes.m#L119
> 
> You will need to evaluate 10 different time steps.

I mean the Python version

**Comment by gurkirt** [comment]
Nope.
