### ISSUE TITLE
Evaluation metric

### ISSUE THREAD

**Issue by aelnouby** [gurkirt/realtime-action-detection#5]
I have checked the paper and the code in `utils/evaluation.py`,  if I understood the code correctly you are using frame mAP not video mAP. So does this mean that the reported mAP in the paper is for frame mAP ?

**Comment by gurkirt** [comment]
can you elaborate what is wrong with video mAP? We only reported video-mAP in the paper.

**Comment by aelnouby** [comment]
Thanks for your reply, I will check the matlab code
