### ISSUE TITLE
Error in Evaluation

### ISSUE THREAD

**Issue by elhamravanbakhsh** [gurkirt/realtime-action-detection#53]
Thanks for your work. when evaluating the model, I'm getting this error: 

Forward Time 2.508
Traceback (most recent call last):
  File "test-ucf24.py", line 225, in <module>
    main()
  File "test-ucf24.py", line 212, in main
    mAP, ap_all, ap_strs = test_net(net, args.save_root, exp_name, args.input_type, dataset, iteration, num_classes)
  File "test-ucf24.py", line 142, in test_net
    ids, counts = nms(boxes, scores, args.nms_thresh, args.topk)  # idsn - ids after nms
ValueError: not enough values to unpack (expected 2, got 0)

**Comment by gurkirt** [comment]
we should not apply nms if number of boxes are zeros. Can you please check shape of boxes going in to nms function.
