### ISSUE TITLE
Download of pretrained brox flow trained model weights

### ISSUE THREAD

**Issue by elenazini17** [gurkirt/realtime-action-detection#55]
Hi
I wonder where would be possible to download pretrained brox flow trained model weights.
Thanks in advance.

**Comment by gurkirt** [comment]
Brox flow is not NN, it is an optimization-based method by Thomas Brox 2004. And it is available in opencv.

**Comment by elenazini17** [comment]
My doubt is related to the fact that at line 117 of train-ucf24.py the pretrained brox flow trained model weigths (broxweigths.pth) is downloaded and placed under folder ucf24/train_data. In that folder I can only find vgg16_reducedfc.pth for rgb-images but not for optical flow. 
I have created the optical flow images using Thomas Brox method but without pretrained model weigths it would be very slow to train the network from scratch. For this reason I was asking where I could download it.

**Comment by gurkirt** [comment]
For initialisation I used the vgg16_reducedfc.pth  for both flows as well as flow net training. There is no difference in initlisation if I remember right
